const adminToken = process.env.ADMIN_TOKEN || 'ne-dos-admin-dev-token';
const baseUrl = process.env.STORE_BASE_URL || 'http://localhost:8787';

async function request(url, options = {}) {
  const res = await fetch(`${baseUrl}${url}`, options);
  const body = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(`${url} -> ${res.status} ${JSON.stringify(body)}`);
  }
  return body;
}

async function main() {
  const health = await request('/api/health');
  if (health.status !== 'ok') throw new Error('Health check failed');

  const meta = await request('/api/meta');
  if (!meta.count || meta.count < 70) throw new Error('Catalog count is unexpectedly low');

  const list = await request('/api/commands?query=weather');
  if (!list.items.some((item) => item.slug === 'weather')) throw new Error('Weather command missing');

  const install = await request('/api/commands/weather/install');
  if (!install.installSnippet || !install.sha256) throw new Error('Install payload missing sha256');

  const slug = `ci-cmd-${Date.now()}`;
  const submission = await request('/api/submissions', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name: slug,
      title: 'CI Command',
      description: 'Generated by integration test',
      author: 'CI',
      category: 'community',
      tags: ['ci', 'test'],
      version: '0.0.1',
      scriptBody: `export default class ${slug.replace(/-/g, '_')} { description() { return 'CI'; } help(term) { term.writeln('help'); } execute(term) { term.writeln('ok'); } }`,
    }),
  });

  const approved = await request(`/api/admin/submissions/${submission.id}/approve`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-admin-token': adminToken,
    },
    body: JSON.stringify({ moderationNote: 'Approved in CI' }),
  });

  if (approved.status !== 'approved') throw new Error('Submission was not approved');

  const published = await request(`/api/commands/${slug}`);
  if (published.slug !== slug) throw new Error('Approved command not published');

  const packageRes = await fetch(`${baseUrl}/api/packages/submitted/${slug}.js`);
  if (!packageRes.ok) throw new Error('Approved package file missing');

  await request(`/api/commands/${slug}/reviews`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ authorName: 'CI Bot', rating: 5, comment: 'ok' }),
  });

  console.log('Integration checks passed.');
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
